name: Clojure CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java: ["8", "11", "16", "17", "21"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          lein: latest # Leiningen

      - name: Get leiningen version
        run: lein version

      - name: Install dependencies
        run: lein deps

      - name: Run tests
        run: lein all test
